# You can remove or comment out `@name = development` if you use the full path,
# but it doesn't hurt to keep it if you prefer to see the active environment.

### Register a new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Kevin",
  "email": "kjh311@gmail.com",
  "password": "yourPassword"
}

### Create a new workout
POST http://localhost:8080/api/workouts
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
  "name": "Arm Workout"
}