# You can remove or comment out `@name = development` if you use the full path,
# but it doesn't hurt to keep it if you prefer to see the active environment.

### Register a new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Kevin",
  "email": "kjh311@gmail.com",
  "password": "yourPassword"
}

### Create a new workout
POST http://localhost:8080/api/workouts
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
  "name": "Arm Workout"
}

### Post a new exercise
POST http://localhost:8080/api/templates
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
  "name": "Bench Press"
}

### Post a new log
POST http://localhost:8080/api/exercises
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
  "templateId": "68d1650572bc6414b71f68b4",
  "date": "2024-05-22T10:30:00Z",
  "sets": [
    {
      "weight": 135,
      "reps": 10
    },
    {
      "weight": 155,
      "reps": 8
    },
    {
      "weight": 165,
      "reps": 6
    }
  ]
}

### get all log
GET http://localhost:8080/api/exercises/template/68d1650572bc6414b71f68b4
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}